using System.Security.Cryptography;
using System.Text;

namespace K8sEscapeRoom.Api.Validation;

/// <summary>
/// Validates proof tokens generated by the CLI.
/// Token format: K8SER|roomId|nonce|timestamp|sha256
/// </summary>
public static class ProofTokenValidator
{
    private const string TokenPrefix = "K8SER";
    private const int ExpectedParts = 5;
    private const int Sha256HexLength = 64;

    /// <summary>
    /// Result of parsing a proof token
    /// </summary>
    public record ParseResult(
        bool IsValid,
        string? Error,
        string? RoomId,
        string? Nonce,
        long? Timestamp,
        string? Sha256
    );

    /// <summary>
    /// Parse a proof token into its components.
    /// Does not validate the hash - use ValidateHash for that.
    /// </summary>
    public static ParseResult Parse(string? token)
    {
        if (string.IsNullOrWhiteSpace(token))
        {
            return new ParseResult(false, "Token is required", null, null, null, null);
        }

        var parts = token.Trim().Split('|');

        if (parts.Length != ExpectedParts)
        {
            return new ParseResult(
                false,
                $"Invalid token format: expected {ExpectedParts} parts separated by '|', got {parts.Length}",
                null, null, null, null
            );
        }

        var prefix = parts[0];
        var roomId = parts[1];
        var nonce = parts[2];
        var timestampStr = parts[3];
        var sha = parts[4];

        // Validate prefix
        if (prefix != TokenPrefix)
        {
            return new ParseResult(false, $"Invalid token prefix: expected '{TokenPrefix}'", null, null, null, null);
        }

        // Validate roomId
        if (string.IsNullOrEmpty(roomId))
        {
            return new ParseResult(false, "Token roomId is empty", null, null, null, null);
        }

        // Validate nonce
        if (string.IsNullOrEmpty(nonce))
        {
            return new ParseResult(false, "Token nonce is empty", null, null, null, null);
        }

        // Parse timestamp (Unix epoch seconds)
        if (!long.TryParse(timestampStr, out var timestamp))
        {
            return new ParseResult(false, "Invalid timestamp: must be Unix epoch seconds", null, null, null, null);
        }

        // Validate sha format
        if (sha.Length != Sha256HexLength || !IsHexString(sha))
        {
            return new ParseResult(false, $"Invalid hash: must be {Sha256HexLength} hex characters", null, null, null, null);
        }

        return new ParseResult(true, null, roomId, nonce, timestamp, sha);
    }

    /// <summary>
    /// Compute the expected hash for verification.
    /// Hash is SHA256(roomId|nonce|timestamp) in hex lowercase.
    /// </summary>
    public static string ComputeHash(string roomId, string nonce, long timestamp)
    {
        var input = $"{roomId}|{nonce}|{timestamp}";
        var bytes = Encoding.UTF8.GetBytes(input);
        var hash = SHA256.HashData(bytes);
        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    /// <summary>
    /// Validate that the provided hash matches the expected hash.
    /// Uses constant-time comparison.
    /// </summary>
    public static bool ValidateHash(string roomId, string nonce, long timestamp, string providedHash)
    {
        var expectedHash = ComputeHash(roomId, nonce, timestamp);
        return CryptographicOperations.FixedTimeEquals(
            Encoding.UTF8.GetBytes(expectedHash.ToLowerInvariant()),
            Encoding.UTF8.GetBytes(providedHash.ToLowerInvariant())
        );
    }

    private static bool IsHexString(string s)
    {
        foreach (var c in s)
        {
            if (!char.IsAsciiHexDigit(c))
            {
                return false;
            }
        }
        return true;
    }
}
